
recipe_list = [
    "https://cookbooks.com/Recipe-Details.aspx?id=8",
"ROCKY ROAD CAKE",
"ingredients",
"1 c. chopped walnuts",
"1 c. seedless raisins",
"1 c. miniature marshmallows",
"1 (6 oz.) pkg. semi-sweet chocolate pieces",
"1 (18 1/2 oz.) pkg. devil's food cake mix with pudding in the mix",
"4 eggs",
"1 c. Hellmann's mayonnaise",
"1 c. water",
"preparation",
"Grease and flour 12-cup fluted tube pan or Bundt pan. In small bowl, mix walnuts, raisins, marshmallows and chocolate pieces. In large bowl with mixer at low speed, beat together cake mix, eggs, mayonnaise and water just until blended. Increase speed to medium; beat for 2 minutes. Stir in nut mixture. Pour in prepared pan. Bake in a 350° oven for 50 minutes or until cake tester inserted in center comes out clean. Cool in pan for 15 minutes. Remove. Cool on rack. If desired, dust with confectioners sugar. Makes 12 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=21",
"CHOCOLATE BOTTOM CUPCAKES",
"ingredients",
"8 oz. cream cheese",
"1 egg",
"1/3 c. sugar",
"1/2 tsp. salt",
"6 oz. pkg. chocolate chips",
"1 1/2 c. flour",
"1/4 c. cocoa",
"1 c. sugar",
"1 tsp. baking soda",
"1/2 tsp. salt",
"1 c. water",
"1/2 c. oil",
"1 Tbsp. vinegar",
"1 tsp. vanilla",
"preparation",
"Blend the first 4 ingredients, then stir in chocolate chips; set aside. Blend the remaining ingredients and fill paper-lined cups with this mixture 1/3 full. Drop 1 tablespoon of the cream cheese mixture into each cup. Bake for 30 to 35 minutes at 350°.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=44",
"CHOCOLATE PUDDING DESSERT",
"ingredients",
"1 c. flour",
"1/2 c. butter or margarine",
"1 c. finely chopped pecans",
"1 (8 oz.) pkg. cream cheese, softened",
"1 c. powdered sugar",
"1 (8 oz.) frozen whipped topping, thawed",
"1 (4 oz.) pkg. instant vanilla pudding mix",
"1 (4 oz.) pkg. instant chocolate pudding mix",
"3 c. milk",
"1 (1.45) milk chocolate bar, grated",
"preparation",
"Mix flour and butter together until they form small crumbs. Stir in pecans. Press into a 9 x 13-inch pan. Bake at 350° for 20 minutes.",
"",
"Beat cream cheese and powdered sugar until smooth. Fold in half of the whipped topping. Spread over cooled crust.",
"",
"Place contents of both packages of pudding mix into large bowl. Add milk and beat slowly with rotary beater for 2 minutes or until smooth. Spread on top of cream cheese mixture.",
"",
"Let stand a few minutes, then carefully spread remaining whipped topping over top. Sprinkle with grated chocolate. Cover and refrigerate.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=71",
"CHOCOLATE DIPPED STRAWBERRIES",
"ingredients",
"1/4 c. semi-sweet chocolate chips",
"2 Tbsp. oil",
"1/4 c. milk chocolate chips",
"1 tsp. vanilla",
"1 pt. strawberries (do not remove stems)",
"preparation",
"In the top of a double boiler, put first 3 ingredients. Heat until liquid. Take off stove and add the vanilla. Dip the strawberries and set them on wax paper until chocolate is hardened.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=74",
"CHOCOLATE COVERED PEANUTS",
"ingredients",
"6 oz. semi-sweet chocolate chips",
"6 oz. butterscotch chips",
"2 Tbsp. peanut butter",
"2 c. Spanish peanuts",
"preparation",
"Melt chips and peanut butter over low heat. Add 2 cups Spanish peanuts. Drop by spoonfuls on waxed paper. Let sit in refrigerator about 30 minutes. Can store at room temperature.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=96",
"CHOCOLATE DRINK MIX",
"ingredients",
"1 (16 oz.) box instant chocolate powder",
"1 (8 qt.) box powdered milk",
"1 (6 oz.) jar powdered cream",
"1/2 c. powdered sugar",
"preparation",
"Combine all ingredients and mix well. Store in airtight container. To serve: Use 1/3 cup mix to 1 cup hot water.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=147",
"CREAM CHEESE SUGAR COOKIES",
"ingredients",
"1 c. sugar",
"1 c. margarine or butter, softened",
"1 (3 oz.) pkg. cream cheese, softened",
"1/2 tsp. salt",
"1/2 tsp. almond extract",
"1/2 tsp. vanilla",
"1 egg, separated",
"2 1/4 c. flour",
"preparation",
"In large bowl combine sugar, margarine, cream cheese, salt, almond extract, vanilla and egg yolk; blend well. Lightly spoon flour into measuring cup; level off. Stir in flour until well blended. Chill dough 2 hours. Heat oven to 375°. On lightly floured surface, roll out dough 1/3 at a time to 1/8-inch thickness. Cut into desired shapes with lightly floured cookie cutters. Place 1 inch apart on ungreased cookie sheets. Leave cookies plain or, if desired, brush with slightly beaten egg white and sprinkle with colored sugar. Bake at 375° for 7 to 10 minutes or until light golden brown. Cool completely. Frost and decorate, if desired. Makes 5 to 6 dozen cookies.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=278",
"BANANA PUDDING",
"ingredients",
"4 eggs",
"2 c. sugar",
"2 c. milk",
"1 tsp. vanilla extract",
"2 tsp. cornstarch",
"6 bananas",
"1 pkg. vanilla wafers",
"preparation",
"Put eggs in a boiler and beat well. Add sugar; mix well. Add milk. Cook slow until it gets to a boil, then add vanilla extract, then cornstarch (mixed in a little milk just to make a paste). Add to the pudding. This will thicken and will be ready to finish. Cut the bananas, put in bowl and add 1 layer of wafers. Add some pudding mix. Continue until all is finished.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=279",
"FRUIT DIP",
"ingredients",
"2 (8 oz.) fruit flavored cream cheese",
"2 (7 oz.) jars marshmallow cream",
"1 small container Cool Whip",
"preparation",
"Cream the cream cheese; add marshmallow cream. When well blended, add Cool Whip. Serve with chunks of cantaloupe, honeydew melon, pineapple, apple, banana, grapes, strawberries, etc.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=304",
"BAGEL BITES",
"ingredients",
"1 tsp. reduced-calorie margarine, softened",
"1/4 tsp. dried whole oregano",
"1/8 tsp. garlic powder",
"2 (1 oz.) frozen mini bagels, thawed and halved",
"preparation",
"Combine first 3 ingredients and spread 1/4 teaspoon margarine mixture over cut sides of each bagel half. Place bagel halves, cut side up, on a baking sheet; broil 6 inches from heat for 1 minute or until golden brown. Yields 4 halves.",
"",
"Per Serving: 94 Calories, 2 g. Fat (19%), 0 mg. Cholesterol and 119 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=308",
"SPINACH DIP",
"ingredients",
"1 (12 oz.) carton 1% low-fat cottage cheese",
"1 (10 oz.) pkg. frozen chopped spinach, thawed and drained",
"1/2 c. low-fat sour cream",
"1/4 c. dry vegetable soup mix",
"1 tsp. lemon juice",
"1 (10 oz.) can water chestnuts, drained and chopped",
"preparation",
"Process in food processor the cottage cheese. Place in bowl. Press spinach between paper towels until barely moist. Add spinach and remaining ingredients to cheese. Stir; cover and refrigerate 3 hours. Serve with crackers or raw vegetables. Yields 3 cups.",
"",
"Per Serving (1 Tablespoon): 14 Calories and .4 g. Fat.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=311",
"PEPPERCORN DIP",
"ingredients",
"1 Tbsp. dried green peppercorns (whole)",
"1 (8 oz.) container reduced-calorie cream cheese (soft-style)",
"3 Tbsp. skim milk",
"1 Tbsp. lemon juice",
"1/4 tsp. garlic powder",
"preparation",
"Crush peppercorns. Combine crushed peppercorns with cream cheese, milk, lemon juice and garlic powder. Beat with an electric mixer using medium speed until smooth. Makes 10 (2 tablespoon) servings.",
"",
"To Serve: Transfer dip to serving bowl and serve with assorted raw vegetable dippers.",
"",
"Per Serving: 53 Calories, 2 g. Fat, 13 mg. Cholesterol and 131 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=317",
"TOSSED ITALIAN SALAD",
"ingredients",
"4 c. fresh spinach, torn",
"2 c. red leaf lettuce, torn",
"1 medium green or sweet yellow pepper, cut in strips (1 c.)",
"2/3 c. thinly sliced radishes",
"1 small red onion, sliced and separated into rings",
"2 Tbsp. red wine vinegar",
"4 tsp. olive oil or salad oil",
"1/2 tsp. garlic salt",
"1/2 tsp. dried oregano, crushed",
"2 Tbsp. grated Parmesan cheese",
"ground pepper (if desired)",
"preparation",
"Salad: Place spinach, lettuce, pepper strips, radish slices and onion rings in a large salad bowl and toss lightly.",
"",
"Dressing: In a screw-top jar combine vinegar, olive oil, garlic salt, oregano and 1 tablespoon water. Cover and shake well to mix.",
"",
"Pour dressing over salad. Toss lightly to coat. Sprinkle Parmesan cheese over salad and toss lightly. Sprinkle with ground pepper (if desired). Serve immediately. Makes 4 servings.",
"",
"Per Serving: 83 Calories, 6 g. Fat, 2 mg. Cholesterol and 364 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=318",
"CHICKEN AND VEGETABLE NOODLE SOUP",
"ingredients",
"8 c. water",
"2 lb. meaty chicken pieces, skinned (breasts, thighs and/or drumsticks)",
"2 Tbsp. instant chicken bouillon granules",
"1 tsp. marjoram, crushed",
"1/2 tsp. pepper",
"1 clove garlic, halved",
"1 (10 oz.) pkg. frozen succotash",
"1 c. chopped onion",
"1/2 c. chopped green or sweet red pepper",
"3 oz. medium or wide noodles (1 1/2 c.)",
"1/4 c. snipped parsley",
"preparation",
"In a 4 to 6-quart Dutch oven, combine water, chicken, bouillon, marjoram, pepper and garlic and bring to a boil. Reduce heat, cover and simmer 1 hour or until chicken is tender. Remove chicken; cool. Debone chicken and cut into bite-size pieces; set aside. Strain broth and return broth to pan. Skim off fat from broth. Add vegetables and noodles and return to boiling. Simmer 10 minutes or until noodles are done. Stir in parsley and chicken. Heat through. Serves 6.",
"",
"Per Serving: 176 Calories, 5 g. Fat, 48 mg. Cholesterol and 437 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=332",
"ROMAINE-VEGETABLE SALAD",
"ingredients",
"1/2 small head romaine lettuce",
"2 stalks celery, thinly sliced",
"1 (16 oz.) pkg. loose-pack frozen broccoli, red peppers, bamboo shoots and straw mushrooms",
"2 Tbsp. water",
"1 Tbsp. white wine vinegar",
"1 Tbsp. cooking oil",
"2 tsp. soy sauce",
"1/4 tsp. five-spice powder",
"preparation",
"Dressing: Mix vinegar, oil, soy sauce and five-spice powder in a custard cup or small bowl; set aside.",
"",
"Clean and tear romaine into bite-size pieces (makes about 3 cups). In a 12-inch skillet combine frozen vegetables and water. Cook over medium-high heat for 3 to 4 minutes or until thawed and just heated through, stirring occasionally. Reduce heat to medium. Stir in dressing and add romaine and celery. Carefully toss about 30 seconds or until romaine begins to wilt. Makes 6 servings.",
"",
"To Serve: Immediately spoon romaine mixture onto salad plates.",
"",
"Per Serving: 49 Calories, 2 g. Fat, 0 mg. Cholesterol and 149 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=359",
"BAKED BEANS",
"ingredients",
"1 (16 oz.) can pork and beans",
"1 Tbsp. mustard",
"2 Tbsp. ketchup",
"1 medium onion, diced",
"1 Tbsp. Worcestershire sauce",
"4 strips bacon, partially cooked",
"2 Tbsp. brown sugar",
"preparation",
"Combine ingredients. Bake at 325° for 45 to 60 minutes. Serves 4 to 6.",
"",
"Per Serving: 129 Calories, 3 g. Fat (20%), 9 mg. Cholesterol and 511 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=363",
"BAKED SQUASH AND APPLES",
"ingredients",
"2 medium cooking apples, cored and cut into 1/2-inch thick round slices",
"lemon juice to taste",
"1 3/4 lb. acorn squash, cut in 1/2-inch thick round slices",
"2 Tbsp. raisins",
"dash of ground cinnamon",
"2 Tbsp. reduced-calorie pancake and waffle syrup",
"preparation",
"Preheat oven to 350°. Brush apple slices with lemon juice to prevent browning. Layer squash and apples in a 1-quart casserole. Sprinkle with raisins and cinnamon. Bake, covered, in a 350° oven for 50 to 60 minutes or until squash is tender.",
"",
"Before serving, drizzle squash and apples with syrup. Makes 4 servings.",
"",
"Per Serving: 106 Calories, 0 g. Fat, 0 mg. Cholesterol and 22 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=365",
"SKILLET SWEET POTATOES",
"ingredients",
"1 lb. sweet potatoes, peeled and sliced*",
"1/2 tsp. finely shredded orange peel",
"1/2 c. orange juice",
"1 Tbsp. molasses or brown sugar",
"1/4 tsp. salt",
"1/4 tsp. ground cinnamon",
"1/8 tsp. ground allspice",
"preparation",
"Bring 1 inch of water to a boil in skillet. Add sweet potatoes; reduce heat, cover and simmer for 20 minutes or until tender. Drain. In a small bowl, combine orange peel, orange juice, molasses or brown sugar, salt, cinnamon and allspice and pour over potatoes. Cook and stir gently until bubbly. Simmer, uncovered, for 5 minutes or until potatoes are glazed, spooning sauce over potatoes occasionally. Makes 4 servings.",
"",
"Note: Can substitute 1 (18 ounce) can sweet potatoes for fresh. Cut potatoes into 2-inch pieces and place in 1-quart casserole. Pour sauce over sweet potatoes and bake, uncovered, in a 350° oven about 30 minutes or until heated through and sauce is bubbly.",
"",
"Per Serving: 134 Calories, 0 g. Fat, 0 mg. Cholesterol and 149 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=377",
"BUTTERMILK BISCUITS",
"ingredients",
"1 c. all-purpose flour*",
"1 tsp. baking powder",
"1/8 tsp. baking soda",
"1/8 tsp. salt",
"1/3 c. buttermilk or sour milk",
"2 Tbsp. cooking oil",
"preparation",
"Stir together flour, baking powder, baking soda and salt in a medium bowl. Stir together buttermilk and oil then pour over flour mixture and mix well. Knead dough gently on a lightly floured surface 10 to 12 times. Roll or pat dough to 1/2-inch thickness. Cut with a 2-inch biscuit cutter, dipping cutter in flour between cuts, and put on an ungreased baking sheet. Bake at 450° for 10 to 12 minutes or until golden. Serve warm. Makes 8 biscuits.",
"",
"Note: If desired, substitute 1/4 cup whole wheat flour or oat bran for 1/4 cup of all-purpose flour.",
"",
"Per Serving (1 Biscuit): 91 Calories, 4 g. Fat, 0 mg. Cholesterol and 99 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=390",
"APPLE CAKE",
"ingredients",
"5 medium apples, peeled and sliced",
"1 pkg. dry red gelatin",
"1/3 c. sugar",
"1 c. flour",
"1 tsp. baking powder",
"1/4 tsp. salt",
"2 Tbsp. butter or oleo",
"1 egg, combined with 1 Tbsp. milk",
"preparation",
"Mix apples with dry gelatin and sugar; set aside. Sift flour, baking powder and salt into bowl. Cut in shortening. Add milk mixture and mix as pie dough. Press into 9 x 12-inch pan, lining sides and bottom. Add apple mixture. Cover with streusel topping. Bake at 350° for 45 minutes. Serves 20.",
"",
"Per Serving: 90 Calories, 2 g. Fat (20%), 14 mg. Cholesterol and 67 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=391",
"CARROT CAKE",
"ingredients",
"1/4 c. margarine, softened",
"1/2 c. sugar",
"1 egg",
"1/4 c. skim milk",
"1/2 tsp. vanilla",
"1/2 c. finely shredded carrots",
"1 c. all-purpose flour",
"1 1/4 tsp. baking powder",
"1/4 tsp. ground cinnamon",
"1/8 tsp. salt",
"dash of ground nutmeg",
"2 tsp. sifted powdered sugar",
"preparation",
"Cream margarine and sugar; beat in egg, milk and vanilla. Stir in carrots. Combine flour, baking powder, cinnamon, salt and nutmeg and add to carrot mixture. Stir until blended. Spray an 8 x 8 x 2-inch baking pan with nonstick spray coating. Pour batter into pan and bake at 350° for 20 to 25 minutes (a toothpick inserted in center should come out clean). Cool. If desired, remove from pan after cooling 10 minutes. Cool completely. Lightly sift powdered sugar evenly over a doily on top of cake; carefully remove doily to have a pretty design. Makes 9 servings.",
"",
"Per Serving: 156 Calories, 6 g. Fat, 31 mg. Cholesterol and 145 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=395",
"BREAD PUDDING",
"ingredients",
"1/4 c. margarine",
"7 to 8 slices bread",
"1 tsp. cinnamon",
"1 c. raisins",
"3 eggs",
"2/3 c. sugar",
"2 c. hot milk",
"1 tsp. vanilla",
"preparation",
"Spread margarine on bread. Cut each slice in 4 squares. Cover bottom of 12 x 7 1/2 x 3/4-inch pan with half of the bread squares. Sprinkle with cinnamon and raisins. Top with remaining bread, margarine side up. Beat eggs until light, adding sugar gradually. Add hot milk slowly to eggs, beating constantly. Add vanilla. Pour egg mixture over bread. Set dish in hot water and bake at 350° for 50 to 60 minutes until set. Serves 16.",
"",
"Per Serving: 145 Calories, 5 g. Fat (30%), 54 mg. Cholesterol and 107 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=400",
"PANCAKES",
"ingredients",
"3/4 c. whole wheat flour",
"1/4 c. all-purpose flour",
"1 1/2 tsp. baking powder",
"1/2 tsp. salt",
"3/4 c. skim milk",
"1 Tbsp. honey",
"1 tsp. cooking oil",
"2 stiffly beaten egg whites",
"2 Tbsp. sugar",
"1 Tbsp. cornstarch",
"3/4 c. water",
"2 Tbsp. frozen orange juice concentrate",
"1 (11 oz.) can mandarin orange sections, drained",
"1 Tbsp. chopped walnuts (fine)",
"preparation",
"Mix flours, baking powder and salt. Mix milk, honey and oil together, then add to dry ingredients. Stir until moistened, then fold in egg whites. While griddle is still cold, spray with vegetable nonstick cooking spray. When griddle is hot, pour 1/4 cup batter on for each pancake. Cook until brown, turning when pancakes have bubbly surfaces. Serve with Orange Sauce. Serves 4.",
"",
"Orange Sauce: Combine sugar and cornstarch; stir in water and orange juice. Cook and stir until thickened and bubbly, then cook, stirring, 2 more minutes. Stir in orange sections and walnuts. Keep warm.",
"",
"Per Serving: 233 Calories, 2 g. Fat, 1 mg. Cholesterol and 244 mg. Sodium.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=413",
"FROZEN POPS",
"ingredients",
"1 (3 oz.) box Jell-O",
"1 c. sugar",
"1 pkg. Kool-Aid (same flavor as Jell-O)",
"2 c. boiling water",
"2 c. cold water",
"preparation",
"Dissolve jello, sugar and Kool-Aid in boiling water. Add cold water. Pour into ice cube trays, small paper cups or frozen pop molds. Insert wooden sticks at an angle for handles after partially frozen. Freeze until firm, 2 to 3 hours.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=423",
"SNACK PIZZA",
"ingredients",
"1 can biscuit mix",
"1 Ragu Pizza Quick sauce",
"grated cheese",
"anything else you like on pizza",
"preparation",
"Let kids roll out their own biscuit dough and put Ragu Pizza Sauce on dough. Then they may add grated cheese and any other toppings they like, such as mushrooms or sausage. Bake at 400° for 8 to 10 minutes.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=424",
"GRILLED SANDWICHES",
"ingredients",
"1 c. chopped ham",
"1/2 c. chopped Velveeta cheese",
"4 hard-boiled eggs, chopped",
"1 small onion, chopped fine",
"4 tsp. relish",
"1/2 c. salad dressing",
"preparation",
"Mix all ingredients together. Spread thick on buns. Wrap in foil. Bake 12 to 15 minutes in 375° oven. Can be frozen before baking.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=448",
"SPAGHETTI",
"ingredients",
"1 lb. lean hamburger",
"1 lb. turkey Italian sausages",
"2 Tbsp. onion flakes",
"1 tsp. garlic powder",
"1 tsp. oregano",
"1/2 tsp. basil",
"dash of salt and pepper",
"5 (8 oz.) cans tomato sauce",
"1 can tomato paste",
"1 c. water",
"preparation",
"Brown hamburger and Italian sausage. Squeeze sausages out of skins. Add seasonings. Add tomato sauce, paste and water; stir. Simmer, uncovered, for 3/4 hour. Make enough pasta to serve 6 to 8.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=451",
"PARTY SANDWICHES",
"ingredients",
"1 loaf day old bread (white or wheat)",
"margarine or Miracle Whip",
"10 slices lunch meat",
"10 slices American cheese",
"preparation",
"Using assorted metal cookie cutters, cut shapes out of bread. Spread with margarine or Miracle Whip. Cut lunch meat and cheese out using same cookie cutters. Garnish each sandwich with pickle slice or green olive. For best results, be sure cookie cutters are sharp.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=458",
"EGGS IN A BASKET",
"ingredients",
"6 slices soft whole wheat bread",
"softened butter",
"6 eggs",
"1/4 c. grated cheese",
"preparation",
"Preheat oven to 400°. Trim crusts off bread; spread both sides of bread with butter. Fit bread slices into cups of muffin tin. Place in oven until lightly toasted; remove from oven. Break an egg into bread and top with cheese. Return to oven and heat 12 to 15 minutes. Slip baskets carefully from the tins. Cool a bit.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=464",
"PIZZA IN A POCKET",
"ingredients",
"1 pkg. pita bread (10 to 12)",
"2 lb. Mozzarella cheese, shredded",
"1 onion, diced",
"1 medium green pepper, diced",
"1 pkg. pepperoni, sliced",
"1/2 to 1 lb. sausage, cooked",
"1/2 lb. mushrooms, sliced",
"2 cans pizza sauce",
"preparation",
"Place all ingredients in separate bowls and have the children create their own pizzas. Place on cookie sheet and bake at 400° until cheese is melted. Great idea for sleepovers and birthday parties.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=608",
"GRILLED STEAK WITH MUSTARD MARINADE",
"ingredients",
"4 lb. lean flank steak, well trimmed",
"1/4 c. grainy-style Dijon mustard",
"2 Tbsp. lime juice",
"1 1/2 Tbsp. reduced-sodium soy sauce",
"1 Tbsp. hoisin sauce",
"1 tsp. Worcestershire sauce",
"1 tsp. finely minced garlic",
"1 tsp. finely minced fresh ginger",
"freshly ground pepper to taste",
"preparation",
"Place the steak in a large glass or ceramic dish. In a medium bowl, whisk the remaining ingredients together. Pour over the meat; coat both sides. Cover and allow to marinate at room temperature for 1 hour or in the refrigerator for 2 to 3 hours. Preheat an outdoor grill or a broiler. Remove the steak from the marinade and grill for 5 minutes on each side or until cooked to the desired doneness, basting occasionally with the marinade. Serve immediately, sliced on the bias. Serves 8.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=611",
"GRILLED VEAL CHOPS",
"ingredients",
"4 veal chops, cut 1-inch thick and well trimmed",
"salt and freshly ground pepper",
"1 1/2 Tbsp. olive oil",
"1 tsp. crumbled Herbes de Provence*",
"preparation",
"Preheat an outdoor grill or a broiler. Place the veal chops in a shallow dish and season with salt and pepper. Combine the oil with Herbes de Provence and brush lightly over both sides of the chops. Allow to sit for 15 to 20 minutes at room temperature. Grill the chops for 5 to 6 minutes per side or until the desired degree of doneness. Serve hot, garnished with parsley or other fresh herbs. Serves 4.",
"",
"*This is a French blend of herbs available in gourmet food shops and some supermarkets. If you can't find it, substitute a blend of 1 tablespoon each crumbled dried basil, oregano and thyme and 1/2 teaspoon each crumbled dried sage and ground rosemary; a pinch of dried lavender is optional.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=633",
"PUMPKIN PIE",
"ingredients",
"1 (16 oz.) can solid pack pumpkin",
"1 (13 oz.) can evaporated skim milk",
"1 egg",
"2 egg whites",
"1/2 c. Bisquick",
"2 Tbsp. sugar",
"8 packets Sweet 'N Low",
"2 tsp. pumpkin pie spice",
"2 tsp. vanilla",
"preparation",
"Heat oven to 350°. Lightly grease 9-inch pie pan. Combine all ingredients and beat for 2 minutes with mixer. Pour into pie pan and bake for 50 minutes or until center is puffed up. Serves 8; contains 112 calories per slice.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=657",
"ITALIAN-STYLE PORK SOUP",
"ingredients",
"1 1/4 to 1 1/2 lb. boneless pork shoulder, cut into 3/4-inch pieces",
"1 Tbsp. oil",
"1 large onion, diced",
"2 cloves garlic, minced",
"1 tsp. each: Italian seasoning and salt",
"1/2 tsp. each: dried basil leaves, fennel seed and pepper",
"1 (16 oz.) can tomatoes, broken up",
"2 c. water",
"1 medium green pepper, diced",
"1 small zucchini, thinly sliced",
"1/3 c. small pasta (bow ties, elbow macaroni or shells)",
"grated Parmesan cheese",
"preparation",
"Brown pork pieces in oil with onion and garlic. Pour off drippings. Sprinkle Italian seasoning, salt, basil, fennel and pepper over pork. Add tomatoes and water; cover tightly and simmer 1 hour. Add green pepper, zucchini and pasta to pork. Increase heat to medium-low and continue cooking, covered, 30 minutes or until vegetables and pasta are done. Sprinkle with Parmesan cheese.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=688",
"GARDEN PASTA",
"ingredients",
"1 jar marinated artichoke hearts (6 oz.)",
"1/2 c. onion, finely chopped",
"1 small clove fresh garlic",
"2 c. fresh tomatoes, diced and peeled",
"1 small bay leaf",
"1/2 tsp. mixed dry Italian herbs",
"1/2 tsp. salt",
"1 Tbsp. fresh basil, finely chopped or 1/2 tsp. dry basil",
"1 Tbsp. parsley, chopped",
"8 oz. noodles (egg or spinach)",
"1/4 c. soft butter",
"1/3 c. Parmesan cheese, grated",
"preparation",
"Drain marinade from artichokes into a 9 or 10-inch skillet. Add onion and press garlic into mixture; simmer until softened. Add tomatoes, bay leaf, Italian herbs, salt and basil. Cover and simmer for 10 minutes. Uncover and continue cooking until sauce thickens slightly, about 10 minutes. Add artichokes (cutting larger ones in halves), and simmer for a few minutes longer. Remove bay leaf and add parsley. Meanwhile, cook noodles in boiling, salted water just until tender. Drain and toss with butter and cheese. Serve with the artichoke sauce and sprinkle with additional cheese, if desired. Makes 3 or 4 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=707",
"PASTA WITH CHEESE AND WALNUTS",
"ingredients",
"8 oz. spinach pasta",
"4 Tbsp. milk",
"8 oz. Philadelphia cream cheese",
"2 (2 3/4 oz.) pkg. Boursin cheese with garlic and herbs",
"2 oz. chopped walnuts",
"2 Tbsp. chopped parsley or chives",
"12 oz. radiatore, ruffles or rotelle pasta",
"1/2 c. butter",
"1 Tbsp. finely chopped garlic",
"1 lb. fresh spinach, well rinsed, trimmed and torn into bite-size pieces",
"1/4 tsp. salt",
"1/4 tsp. freshly ground pepper",
"4 plum tomatoes or 2 medium tomatoes, seedless and chopped (about 1 1/2 c.)",
"4 oz. goat cheese, crumbled",
"preparation",
"Cook pasta. At the same time in large saucepan melt butter over medium heat. Add garlic and sauté 30 seconds. Add spinach, salt and pepper; sauté 2 minutes or until spinach is wilted. Transfer pasta to a warm serving bowl. Add spinach, tomatoes and goat cheese; toss well. Makes 4 servings, containing 645 calories each.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=712",
"SPINACH MEATBALLS",
"ingredients",
"1 (10 oz.) pkg. frozen chopped spinach, thawed",
"1 lb. ground beef",
"1 egg, lightly beaten",
"1/2 c. Italian style bread crumbs",
"1/2 c. finely chopped onions",
"1/2 tsp. oregano leaves, crushed",
"1 (15 1/2 oz.) jar marinara spaghetti sauce",
"cooked pasta",
"grated Parmesan cheese",
"preparation",
"Drain spinach, squeezing out as much liquid as possible. Combine with beef, egg, bread crumbs, onions and oregano in medium bowl. Mix well. Shape into 1 inch balls. Place in single layer on jelly roll pan. Bake at 425° for 5 minutes. Turn and bake another 5 minutes. Reduce oven to 350°. Remove meatballs and place in shallow 1 quart casserole. Pour sauce over meatballs, cover and bake 20 to 25 minutes or until meatballs are cooked through and sauce is hot. Serve over pasta, sprinkled with Parmesan cheese. Makes 4 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=733",
"ANGEL HAIR PASTA WITH CRAB",
"ingredients",
"8 oz. angel hair pasta",
"2 Tbsp. margarine",
"1/4 c. oil",
"1/2 c. sliced green onions",
"1 clove garlic, minced",
"2 medium-sized tomatoes, peeled and chopped",
"1 Tbsp. lemon juice",
"1/2 lb. cooked crab",
"1 Tbsp. parsley",
"preparation",
"Cook noodles according to package directions. In frying pan over medium heat, place margarine and oil. When margarine is melted, add green onions, garlic and tomatoes. Cook, stirring until mixture boils. Adjust heat so mixture boils gently and cook for 2 minutes. Mix in lemon juice, crab and parsley. Cook just until crab is heated. Season to taste with salt and pepper. Spoon sauce over pasta. Lift and mix pasta gently. Makes 4 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=766",
"GLAZED CHICKEN WINGS",
"ingredients",
"2 c. duck sauce",
"4 oz. honey",
"3 Tbsp. lemon juice",
"3 Tbsp. soy sauce",
"3 Tbsp. brown sugar",
"2 to 3 lb. chicken wings or wingettes (little wings without tips)",
"preparation",
"Mix first 5 ingredients in a bowl, set aside. Cut chicken at joints; place in a row in roasting pan. Place the sauce over the wings and bake until golden brown in a 350° oven.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=794",
"CHICKEN CORN CHOWDER",
"ingredients",
"2 Tbsp. chopped onion",
"1 Tbsp. chopped green pepper",
"1 Tbsp. butter or margarine",
"1 (10 1/2 oz.) can condensed cream of chicken soup",
"1 c. milk",
"1/2 c. water",
"1 c. chopped, cooked chicken",
"1 (8 3/4 oz.) can whole kernel corn (undrained)",
"preparation",
"Cook onion and green pepper in butter until tender. Add remaining ingredients. Heat, stirring occasionally. Makes 2 or 3 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=899",
"SHRIMP DIP",
"ingredients",
"2 (4 1/2 oz.) cans shrimp, cooked and deveined",
"1 c. mayonnaise",
"1 c. sour cream",
"1/4 c. green onions",
"2 Tbsp. lemon juice",
"1/4 tsp. salt",
"1/8 tsp. pepper, ground",
"2 dashes of Tabasco sauce",
"preparation",
"Stir all ingredients until mixed well. Cover and chill. Serve with assorted crackers. Makes 3 cups.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=937",
"FISH AND CHIPS",
"ingredients",
"1 1/2 lb. fresh fish fillets (sole, flounder, haddock or cod)",
"2 eggs, separated",
"1/2 c. beer",
"1/4 c. milk",
"1 c. all-purpose flour",
"1/2 tsp. seasoned salt",
"1/4 tsp. seasoned pepper",
"preparation",
"Cut fillets into pieces, about 3 x 1 1/2-inches. Place on paper towels to dry. Beat egg yolks until thick and light. Blend in beer, milk, flour and seasonings. Mix until smooth. Beat egg whites stiff but not dry; fold in. Pat fillets dry. Dip into batter, a few pieces at a time; lift out and drain slightly with fork or slotted spoon. Fry in deep fat heated to 375° for 2 to 3 minutes until golden brown and puffed. Drain on absorbent paper. Serve with French fried potatoes.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=984",
"MEXICAN CHEESE SOUP",
"ingredients",
"1/2 c. finely chopped onion",
"1/2 c. shredded carrots",
"1/2 c. thinly sliced celery",
"1/3 c. butter or margarine",
"1/3 c. flour",
"1 tsp. paprika",
"1 tsp. dry mustard",
"1 tsp. Worcestershire sauce",
"1 (14 1/2 oz.) can chicken broth",
"1 c. milk",
"1/2 tsp. liquid smoke",
"1 c. shredded Cheddar cheese",
"canned chopped green chilies",
"tortilla chips (nacho cheese)",
"preparation",
"In a medium saucepan cook onion, carrots and celery in butter or margarine until tender. Stir in flour, paprika, dry mustard and Worcestershire sauce until blended. Add chicken broth and milk. Stir over medium heat until mixture thickens and bubbles. Stir in liquid smoke. Reduce heat to very low, then stir in cheese. Simmer 10 minutes. Ladle soup in bowls; top soup with chopped chilies and 4 or 5 tortilla chips. Makes 4 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=995",
"CHUNKY POTATO SOUP",
"ingredients",
"2 Tbsp. butter",
"1 1/2 c. chopped onion",
"1 bay leaf",
"1/2 tsp. dried thyme",
"4 c. cubed potatoes",
"2 cans chicken broth",
"1/8 tsp. pepper",
"1 c. milk",
"1/2 tsp. salt",
"sliced green onions (optional)",
"preparation",
"In large saucepan, melt butter; add onions, bay leaf and thyme. Cook until onions are translucent. Add potatoes, broth and pepper. Boil until potatoes are tender. Remove bay leaf. With slotted spoon, remove about 2 cups of the potatoes and onions to a bowl. Puree remaining soup in a blender and return to saucepan. Stir in milk and the reserved potatoes and onions. Season with salt and heat just to boiling. Garnish with green onions, if desired.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1005",
"SPINACH SOUP",
"ingredients",
"1 c. green onions, firmly chopped",
"6 Tbsp. margarine or butter",
"2 c. dry nondairy creamer",
"5 c. chicken broth",
"2 medium potatoes, thinly sliced",
"2 medium carrots, sliced",
"1/4 c. uncooked regular rice",
"1 (10 oz.) pkg. frozen spinach",
"preparation",
"Cook onions in butter until soft. Add nondairy creamer all at once to boiling chicken broth and stir to blend. Add potatoes, carrots and rice to cooked onions; stir. Cover and cook 15 minutes; add to broth. Add frozen spinach and continue boiling for 15 minutes more, stirring often to prevent sticking. Salt and pepper to taste. Can be frozen and reheated.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1034",
"SAUSAGE STEW",
"ingredients",
"1 1/2 to 2 lb. smoked sausage",
"4 or 5 potatoes",
"1 or 2 medium onions",
"2 to 3 Tbsp. paprika",
"salt to taste",
"dumplings (recipe follows)",
"preparation",
"In large pot put thin sliced sausage, sliced potatoes and onions. Cover with at least 1 inch water and paprika. Salt to taste. While this is cooking, make dumplings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1063",
"CREAMY FRUIT DIP",
"ingredients",
"8 oz. plain lo-cal yogurt",
"4 Tbsp. lo-cal preserves (no sugar)",
"1/2 tsp. ground allspice",
"1/2 tsp. lemon juice",
"preparation",
"Combine all ingredients. Whip until fluffy. Chill thoroughly. Yield: 1 cup.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1073",
"PIZZA SNACK",
"ingredients",
"1/4 c. tomato puree",
"1/4 tsp. garlic powder",
"1/4 tsp. onion powder",
"1/4 tsp. oregano",
"1 slice bread or 1/2 English muffin",
"1 oz. cheese",
"preparation",
"Toast bread. Put tomato, seasonings and cheese on toast. Broil for 1 to 5 minutes. Good with salad. Equals 1 bread, 1 fat, 1 meat, 1/2 vegetable exchange on diabetic diet.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1076",
"SAVORY CHEESE SPREAD",
"ingredients",
"16 oz. 1% low-fat cottage cheese",
"1/4 c. polyunsaturated margarine",
"1 1/2 tsp. paprika",
"1 tsp. dry mustard",
"1 tsp. caraway seed",
"2 Tbsp. thinly sliced scallions (white and green parts)",
"1 Tbsp. capers",
"preparation",
"Puree cottage cheese in blender; add margarine. Blend well. Add other ingredients. Blend well. Serve at room temperature. Yields 2 3/4 cups; 35 calories per serving.",
"",
"Approximate nutrient values per serving: 3 g. protein, 2 g. fat, 1 g. carbohydrates, 105 mg. sodium and 1 mg. cholesterol. Exchange: 1 fat.",
"",
"For diabetic, low calorie, low fat and low sodium diets.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1078",
"LOW CALORIE PARTY MIX",
"ingredients",
"4 tsp. margarine",
"1 Tbsp. Worcestershire sauce",
"1/8 tsp. onion powder",
"1/8 tsp. garlic powder",
"1 1/2 oz. donut shaped cereal (about 1 c.)",
"1 1/2 oz. biscuit shaped cereal (Chex, about 3/4 c.)",
"1 oz. broken pretzels",
"preparation",
"Melt oleo with Worcestershire sauce, onion and garlic powder. Stir until combined. Add cereals and pretzels. Stir together gently until cereals and pretzels are coated. Bake in 250° oven for 20 to 25 minutes or until crispy. Divide into 4 equal servings of 145 calories each.",
"",
"Diabetic or Weight Watchers exchanges are: 1 bread serving, 1 fat serving, 25 optional calories.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1085",
"MACARONI SALAD",
"ingredients",
"1 c. uncooked elbow macaroni",
"1/4 c. mayonnaise",
"1 Tbsp. vinegar",
"1 tsp. prepared mustard",
"3/4 c. chopped celery",
"1/2 c. sliced green onion",
"2 Tbsp. sweet pickle relish",
"1 Tbsp. chopped pimento",
"preparation",
"Cook macaroni, drain. Mix mayonnaise, vinegar and mustard in large bowl. Add macaroni and remaining ingredients. Chill.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1090",
"ORANGE SALAD",
"ingredients",
"1 (8 oz.) carton low-fat cottage cheese",
"1/2 c. low-fat mayonnaise",
"1 (11 oz.) can mandarin oranges, drained",
"1 pkg. sugar-free orange gelatin",
"preparation",
"Combine all ingredients. Mix well. Chill.",
"",
"Each serving equals 1 meat, 1 1/2 fruits and 3 fat exchanges.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1129",
"SAVORY PORK CHOPS",
"ingredients",
"4 loin chops",
"1/2 tsp. salt",
"1/2 tsp. marjoram",
"1/8 tsp. thyme",
"1/8 tsp. sage",
"3/4 c. chicken broth",
"1/2 tsp. grated orange rind",
"1/8 tsp. ground ginger",
"preparation",
"Preheat oven to 300°. Trim fat from meat and cook, using 1 tablespoon liquid fat. Combine salt, marjoram, thyme and sage. Sprinkle on meat and press with fingers. Brown meat on both sides (using cooked fat). Transfer to shallow dish. Combine chicken broth, orange rind and ginger. Pour over chops. Cover and bake 45 minutes. One chop contains 285 calories.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1167",
"BANANA BREAD",
"ingredients",
"2 Tbsp. oleo",
"2 c. flour",
"1/8 tsp. salt",
"1 1/2 tsp. soda",
"2/3 c. fructose",
"2 eggs, lightly beaten",
"1 tsp. vanilla",
"1/2 c. buttermilk",
"3 ripe bananas, mashed",
"preparation",
"Cream oleo and 1 cup flour mixed with salt, soda and fructose. Add beaten eggs and mix well. Add rest of flour and buttermilk alternately, then vanilla and mashed bananas. Put in greased pan (bottom only) and bake at 350°.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1174",
"FRENCH TOAST",
"ingredients",
"1 egg",
"1 Tbsp. milk",
"noncalorie sweetener",
"4 drops vanilla extract",
"dash of salt",
"preparation",
"Mix until frothy. Dip slice of bread in mixture and put in pan with 1 tablespoon butter. Fry until browned.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1199",
"FRUIT CAKE",
"ingredients",
"1/3 c. cooking oil",
"1 1/2 c. unsweetened applesauce",
"2 Tbsp. liquid sweetener",
"1 large egg, beaten",
"2 c. flour",
"2 tsp. baking powder",
"1/2 tsp. baking soda",
"2 Tbsp. cocoa",
"1/4 tsp. salt",
"1 tsp. cinnamon",
"1/2 tsp. ground nutmeg",
"1/2 tsp. ground cloves",
"1/2 c. seedless raisins",
"1/2 c. chopped dates",
"1/4 c. chopped nuts",
"1 tsp. lemon rind",
"preparation",
"Add oil to applesauce and egg. Add sweetener. Sift flour, baking powder, baking soda, cocoa, salt, cinnamon, nutmeg and cloves. Add lemon rind, raisins, dates and nuts to dry ingredients. Then add to applesauce mixture. (It will be thick.) Pour mixture into greased loaf pan. Bake at 325° for 1 hour.",
"",
"Exchanges: 1 bread, 1 1/2 fat.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1258",
"PARTY FRUIT PUNCH",
"ingredients",
"4 large cans pineapple juice, unsweetened",
"1 large can grapefruit juice, unsweetened",
"1 large can frozen lemonade, diluted",
"1 large can frozen orange juice, diluted",
"2 small cans frozen limeade, diluted",
"4 to 5 drops peppermint extract",
"2 large cans crushed pineapple, undrained",
"2 Tbsp. grenadine syrup, ginger ale or Sprite",
"4 c. sugar",
"preparation",
"Mix all ingredients together (except ginger ale or Sprite) in a very large container. Stir until sugar is dissolved. (Sugar may be omitted if you feel that some you will be serving are diabetic!) Pour into 5 to 6 five quart plastic buckets. (Ice cream buckets are excellent for freezing.) Put in freezer. Serves 150 to 200.",
"",
"When ready to serve, add 2 bottles ginger ale (or 2 liters Sprite) to the bucket of punch. Take out of freezer 3 to 4 hours before serving. This is a bright yellow punch; can be poured over 1 quart pineapple sherbet for a lighter, frothy look. Will be a slush.",
"",
"For Green Punch: Add 1 quart lime sherbet and a few drops green food coloring. Add slowly and stir to keep it light in color.",
"",
"For Red Punch: Add 2 (10 ounce) packages frozen, sliced strawberries and few drops red food coloring.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1340",
"ZUCCHINI BREAD",
"ingredients",
"2/3 c. soy margarine",
"4 eggs (Energ Egg Replacer)",
"3 c. shredded zucchini",
"2 1/2 tsp. baking powder (Rumford)",
"1 tsp. ground cinnamon",
"2/3 c. raisins",
"2 tsp. vanilla (alcohol free)",
"2 2/3 c. dry sweetener (dehydrated cane juice or fructose)",
"3 1/2 c. unbleached flour",
"1 1/2 tsp. sea salt (optional)",
"2/3 c. coarsely chopped nuts",
"2/3 c. water",
"preparation",
"Preheat oven to 350°. Grease bottoms only of loaf pans, 9 x 9 x 3-inch, or 3 loaf pans, 8 1/2 x 4 1/2-inches. Mix soy margarine and dry sweetener in large bowl. Add eggs, zucchini and water. Blend in flour, baking powder and cinnamon. Stir in nuts and raisins. Pour into pans. Bake until wooden pick inserted in center comes out clean or about 60 to 70 minutes; cool slightly. Loosen sides of loaves from pans. Cool completely before slicing.",
"",
"To store, wrap and refrigerate no longer than 10 days. Serves as a dessert.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1364",
"CHICKEN WINGS ON THE GRILL",
"ingredients",
"1 lb. chicken wings",
"1/2 bottle Italian dressing",
"preparation",
"Marinate chicken wings in the Italian dressing overnight. Grill over low heat for 30 minutes; turn and grill 30 minutes more. Enjoy!",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1418",
"GRILLED GARLIC SHRIMP",
"ingredients",
"2 lb. large unshelled shrimp, deveined",
"1/2 c. melted, unsalted butter",
"1/2 c. olive oil",
"1 Tbsp. minced shallots or green onions",
"3 large peeled cloves garlic",
"1 tsp. salt",
"1 1/2 Tbsp. fresh lemon juice",
"1/4 c. minced parsley",
"salt and freshly ground pepper",
"parsley sprigs (garnish)",
"preparation",
"Wash shrimp in cold water and dry well. Pour butter and olive oil into a 3-quart shallow bowl. Add shallots. Chop garlic with salt on a cutting board (this helps eliminate the strong garlic aftertaste). Add garlic and salt mixture to bowl. Roll shrimp in this mixture until well coated. Sprinkle with lemon juice and parsley. Marinate at least 30 minutes, turning shrimp several times.",
"",
"Place shrimp on gas grill over medium flame and grill 5 to 7 minutes on each side, depending on size of shrimp. Salt and pepper to taste. Serve in individual dishes and spoon heated marinade over them. Garnish with parsley. Yield: 6 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1423",
"BLACK PEPPER STEAK",
"ingredients",
"1 (1 1/2 to 2 lb.) sirloin steak, 1 1/2 to 2-inches thick",
"2 large onions, thinly sliced",
"1 c. red wine vinegar",
"1/2 c. vegetable oil",
"1/3 c. firmly packed brown sugar",
"1 clove garlic, minced",
"1/4 tsp. salt",
"1/4 tsp. dried whole marjoram",
"1/4 tsp. dried whole rosemary, crushed",
"3 drops hot sauce",
"1 Tbsp. plus 1 tsp. coarsely ground pepper, divided",
"tomato wedges",
"fresh parsley sprigs",
"preparation",
"Place steak in a large shallow dish. Combine onions, vinegar, oil, brown sugar, garlic, salt, marjoram, rosemary and hot sauce; pour over steak. Cover and refrigerate 3 hours, turning occasionally. Remove steak from marinade. Press 2 teaspoons pepper onto each side of steak. Grill over hot coals 15 minutes on each side or to desired degree of doneness. Place steak on serving platter; garnish with tomato wedges and fresh parsley. To serve, cut into serving pieces. Yield: 3 to 4 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1433",
"GRILLED FISH AND SHRIMP",
"ingredients",
"4 fish fillets",
"1 lb. large shrimp, cleaned",
"1/2 c. butter",
"juice of 2 lemons",
"1 or 2 cloves garlic, pressed",
"Greek seasoning",
"1 bell pepper",
"1/2 c. onion, chopped",
"1 tomato, chopped",
"preparation",
"Melt butter; add lemon juice and garlic and simmer 1 minute. Season fish and shrimp lightly with Greek seasoning. Place fish and shrimp in a large sheet of heavy foil with top loosely opened. Baste heavily with lemon butter and garlic sauce. Add chopped tomato, onion and green pepper. Place on an outdoor grill and cook about 5 minutes. This may be baked in oven with foil closed.",
"",
"Scallops may be substituted for shrimp.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1477",
"GRILLED CORN",
"ingredients",
"tender sweet corn",
"butter",
"salt and pepper",
"preparation",
"Strip husks down to the end of the cob, but do not tear off. Remove silk. If desired, soak in salted ice water to which 1/2 cup milk has been added for about 20 minutes; drain well. Brush with softened butter and sprinkle with salt and pepper. Bring husks up around the corn. Wrap each ear securely in a double thickness of aluminum foil. Twist the ends well. Barbecue on briquets 10 minutes, turning once.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1490",
"GRILLED EGGPLANT",
"ingredients",
"1/2 c. olive oil",
"1/4 c. red wine vinegar",
"1/2 lemon (for the juice)",
"2 cloves garlic, crushed",
"1 Tbsp. chopped rosemary leaves",
"1 Tbsp. chopped oregano leaves",
"1 tsp. salt",
"1/2 tsp. ground pepper",
"2 small or 1 large eggplant, cut into 1-inch thick pieces",
"preparation",
"Combine all the ingredients for the marinade. Place in a flat-bottomed pan, such as a 9 x 13-inch cake pan. Place the eggplant slices in the pan. Allow the slices to soak on each side for at least 10 minutes per side. Grill over hot coals until soft. Occasionally drizzle with the marinade. When eggplant is very tender, serve immediately. Serves 4.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1507",
"GRILLED CORNBREAD",
"ingredients",
"1 Tbsp. butter",
"2 large eggs",
"2/3 c. milk",
"8 oz. can creamed corn",
"2 (12 oz.) pkg. corn muffin mix",
"1/2 c. shredded Cheddar cheese",
"4 slices bacon, crisply cooked and crumbled",
"preparation",
"In an 8 or 9-inch foil pan, melt butter. Turn off heat; swirl butter to coat bottom and sides of pan. In large bowl beat eggs and milk to blend; stir in creamed corn. Add muffin mix and stir only until moistened. Turn into prepared pan. Sprinkle with cheese and bacon. Place pan on barbecue grill 6 inches above medium hot coals. Loosely cover top with foil. Cook about 30 minutes. Makes 8 to 10 servings.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1585",
"BANANA CREAM PIE",
"ingredients",
"bittersweet chocolate, shaved or chocolate bits",
"2/3 c. sugar",
"1 pkg. unflavored gelatin",
"1 c. light cream",
"1/4 c. dark rum",
"1 c. sour cream",
"6 medium ripe bananas",
"1 c. heavy cream",
"1/3 c. cake flour",
"1/4 tsp. salt",
"3 large egg yolks, beaten",
"1 1/2 tsp. vanilla",
"1 (10-inch) pie crust, baked and cooled",
"2 Tbsp. sugar",
"preparation",
"Sift together in top of double boiler, sugar, flour, gelatin and salt. Add light cream; whisk until well combined. Place over simmering water; add egg yolks. Continue whisking until mixture starts to thicken. Remove from double boiler and beat until smooth. Stir in rum and 1 teaspoon vanilla. Stir in sour cream; beat until smooth. Place in refrigerator until mixture starts to set, 20 minutes. Watch so it does not get too thick. Line bottom of crust with banana slices; pour custard over and refrigerate at least 4 hours. Just before serving, top with whipped cream, confectioners sugar and 1/2 teaspoon vanilla.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1680",
"PLAKI (GREEK FISH)",
"ingredients",
"2 lb. haddock",
"2 lb. onions, chopped",
"5 cloves garlic, minced",
"lemon juice",
"salt and pepper to taste",
"raisins",
"olive oil",
"crushed tomatoes",
"mint",
"parsley",
"water",
"preparation",
"Sauté onions and garlic in small amount olive oil. Clean fish and rub with lemon juice and salt. Add to pot. Pour crushed tomatoes over and small amount of water. Sprinkle generously with mint flakes, parsley and raisins. Bring to boil; cover and simmer for 20 to 30 minutes or until tender.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1853",
"TACO SALAD",
"ingredients",
"1 onion, chopped",
"4 tomatoes, chopped",
"1 head lettuce, broken into pieces",
"4 oz. grated cheese",
"8 oz. French dressing",
"hot sauce",
"1 (5 1/2 oz.) pkg. taco flavored Doritos",
"1 lb. ground beef",
"1/4 tsp. salt",
"1 (15 oz.) can kidney beans",
"preparation",
"Chop onions, lettuce and tomatoes. Toss with grated cheese, French dressing and hot sauce to taste. Crunch and add Doritos chips. Brown and drain ground beef. Add salt and drained kidney beans. Simmer 10 minutes, then add to cold salad. Decorate with chips, tomato slices and avocado slices, if desired. Serve pronto!",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1915",
"BEEF FAJITAS",
"ingredients",
"3 lb. tri-tip or bottom sirloin beef",
"1/3 c. margarine",
"2 medium sized onions, cut into 1/4-inch slices",
"2 medium sized green peppers, cut into 1/4-inch slices",
"1 Tbsp. seasoning salt",
"8 medium tomatoes, cut into wedges",
"lemon wedges to garnish",
"preparation",
"Place meat in shallow pan. Pour marinade over and refrigerate 3 hours. Remove meat from marinade and cut into 1/2 x 3-inch strips. Melt margarine in 1 large skillet. Add onions, peppers and seasoning salt; sauté until tender. Place meat into large cast-iron skillet and sear over medium heat until browned. Add vegetables. Place tomatoes over both meat and vegetables. Garnish with lemon wedges. Serves 6.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=1917",
"BEEF CHIMICHANGA",
"ingredients",
"1 doz. large flour tortillas",
"1 lb. ground beef, cooked and drained",
"1 lb. grated yellow and Jack cheese, mixed",
"1 small can chopped green chilies",
"1 medium size can refried beans",
"preparation",
"Add small amount of each ingredient in the middle of a flour tortilla and roll into a 2-inch diameter size (makes a burrito). Deep-fry each burrito in light oil until brown and crisp. Drain on paper towels. Top each serving with shredded lettuce, diced tomatoes, chopped green onions (optional) and more grated cheese. Garnish with pitted ripe olives (sliced), avocados (optional) and sour cream.",
"",
"Prepare for many compliments! Also, if you like it spicy, add more green chilies to topping.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2041",
"STRAWBERRY DIVINITY",
"ingredients",
"3 c. sugar",
"3/4 c. light corn syrup",
"3/4 c. strawberry preserves",
"2 egg whites",
"1 (3 oz.) pkg. strawberry jello",
"1 c. chopped nuts",
"preparation",
"Cook preserves over low or medium heat until the mixture gets thin or melts. Combine sugar, corn syrup and the melted preserves in a heavy saucepan. Cook over medium heat, stirring constantly until sugar dissolves. If sugar crystals form on sides of pan, wipe them off. Continue cooking to the hard-ball stage (252°). Meanwhile, beat egg whites until stiff, but not dry; blend in jello. When syrup reaches 252°, pour in a thin stream over egg whites, beating constantly with electric mixer on medium speed. Beat as long as possible, using wooden spoon if mixture becomes too stiff for mixer. Add nuts and pour into lightly buttered square pan. When cool and firm, cut into 36 pieces. If divinity has not hardened by the time it is completely cool, put in the freezer for an hour or so. Makes about 2 pounds.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2054",
"CANDIED PECANS",
"ingredients",
"3 c. pecans",
"2 Tbsp. margarine",
"1/2 c. Karo light corn syrup",
"1/2 c. sugar",
"1/4 tsp. ground cinnamon",
"preparation",
"Place pecans in 13 x 9 x 2-inch baking pan. Heat in 250° oven for 5 minutes. In a 2-quart saucepan, melt margarine over medium heat. Stir in corn syrup, 1/4 cup of the sugar and cinnamon. Stirring constantly, bring to boil over medium heat. Boil, without stirring, 5 minutes. Pour syrup over pecans, stirring constantly to coat evenly. Bake in 250° oven, stirring several times; immediately spread out on greased cookie sheets. Cool slightly. With 2 forks, separate pecans. Cool completely. Store in tightly covered container. Makes 3 cups.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2170",
"SAUSAGE BALLS",
"ingredients",
"1 lb. sausage",
"3 1/2 c. Bisquick",
"1 (10 oz.) pkg. shredded Cheddar cheese",
"preparation",
"Combine all ingredients with hands. Shape loosely in small 1-inch balls. Bake at 350° for 15 to 20 minutes. These can be frozen.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2392",
"BUTTERMILK PIE",
"ingredients",
"1 c. butter or margarine, melted",
"1/2 c. flour",
"3 c. sugar",
"1 c. buttermilk",
"1 tsp. salt",
"2 tsp. vanilla",
"6 eggs, beaten",
"2 (9-inch) deep-dish unbaked pie shells",
"preparation",
"Mix sugar and butter until well creamed. Add beaten eggs. Slowly add flour, vanilla and milk. Beat at high speed until mixed well. Pour into unbaked pie shells. Bake at 350° until brown on top, about 5 minutes. You should put foil on edges of crusts to keep them from browning too fast.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2413",
"RAVE REVIEWS COCONUT CAKE",
"ingredients",
"1 pkg. yellow cake mix",
"1 small pkg. vanilla instant pudding",
"1 1/3 c. water",
"4 eggs",
"1/4 c. oil",
"2 c. coconut",
"1 c. chopped pecans",
"preparation",
"Blend cake mix, pudding mix, water, eggs and oil in a large mixing bowl. Beat at medium speed for 4 minutes. Stir in coconut and pecans. Pour into 3 greased and floured 9-inch layer pans. Bake at 350° for 35 minutes. Cool in pans for 15 minutes. Remove and cool on rack. Fill and top with Coconut-Cream Cheese Frosting.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2416",
"PAW PAW",
"ingredients",
"1 c. butter (not margarine)",
"2 c. sugar",
"2 c. cake flour",
"6 eggs (medium)",
"1 tsp. pure vanilla",
"preparation",
"Cream together butter and sugar until sugar is fairly well dissolved. Add eggs, one at a time, while continuing to beat. Add vanilla. Fold in flour. Grease and flour tube pan. Put waxed paper in bottom of pan. Pour mix into pan. Bake in 325° oven for 1 hour.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2492",
"BACON APPETIZERS",
"ingredients",
"1 lb. bacon",
"1 c. mayonnaise",
"8 oz. Gouda cheese, grated",
"cocktail rye bread",
"preparation",
"Fry bacon until crisp; drain on paper towels, then crumble. Mix bacon, mayonnaise and cheese together. Place mixture on cocktail rye bread. Heat until cheese is bubbly at 350°. Yields about 20 appetizers.",
"",
"https://cookbooks.com/Recipe-Details.aspx?id=2513",
"HOT CRAB DIP",
"ingredients",
"1 (6 1/2 oz.) can crab meat",
"2 Tbsp. lemon juice",
"2 drops Tabasco sauce",
"1/4 c. light cream",
"1 tsp. finely chopped onion",
"1 tsp. garlic flakes",
"2 (3 oz.) pkg. cream cheese",
"1/4 c. mayonnaise",
"1/8 tsp. salt",
"1/4 tsp. Worcestershire sauce",
"preparation",
"Drain crab meat. Pour lemon juice over crab meat. Combine remaining ingredients. Add to crab meat and juice. Put in saucepan over low heat, stirring occasionally until creamy. Serve with any type of crackers."
]






////////////////////////////////////////////////////////////////////////////////////////
////                                                                                ////
////                                                                                ////
////                                   IMPLEMENTATION                               ////
////                                                                                ////
////                                                                                ////
////////////////////////////////////////////////////////////////////////////////////////


class Recipe {
    constructor(name, ingredients, preparation, url) {
        this.name = name;
        this.ingredients = ingredients; 
        this.preparation = preparation;
        this.url = url;
    }
}




var recipes = [];


var i = 0;
var name_flag = false;
var ingredient_flag = false;
var prep_flag = false;
var prep = "";
var name = "";
var ings = []
var url = "";
while (i != recipe_list.length) {
    line = recipe_list[i];
    if(line == "preparation"){
        ingredient_flag = false;
    }
    if (line[0] == "h" && 
        line[1] == "t" &&
        line[2] == "t" &&
        line[3] == "p") {
        prep_flag = false;
    }
    if (name_flag){
        name = line;
        name_flag = false;
    }
    if (ingredient_flag) {
        ings.push(line)
    }
    if(prep_flag){
        prep += line;
        prep += '\n';
    }
    if (line[0] == "h" && 
        line[1] == "t" &&
        line[2] == "t" &&
        line[3] == "p") {
        recipes.push(new Recipe(name, ings, prep, url))
        url = line;
        name = "";
        ings = [];
        prep = "";
        name_flag = true;
    }
    if(line == 'ingredients'){
        ingredient_flag = true;
    }
    if (line == "preparation"){
        prep_flag = true;
    }
    i += 1;
}
recipes.push(new Recipe(name, ings, prep))




function searchRecipe(ingredient, recipe) {
    const lower_recipe = recipe.toLowerCase();
    var result = lower_recipe.includes(ingredient);
    return result;
}


function search_matches(pantry) {
    var matches = []
    var i = 0;
    while(i != recipes.length){
        var j = 0;
        var count = 0;
        while(j != pantry.length){
            var k = 0;
            while(k != recipes[i].ingredients.length){
                var flag = searchRecipe(pantry[j], recipes[i].ingredients[k])
                if(flag){
                    count += 1;
                }
                k += 1;
            }
            j += 1;
        }
        matches.push(count);
        i += 1;
    }
    return matches
}

function find_min(values, index) {
    var min = 0
    var i = 1
    while (i != index.length){
        if(values[index[i]] < values[index[min]]){
            min = i;
        }
        i += 1;
    }
    return min;
}

function top_five(arr) {
    if(arr.length < 5){
        return;
    }
    var index = [0, 1, 2, 3, 4];
    var i = 5;
    while (i != arr.length){
        min = find_min(arr, index);
        if(arr[i] > arr[index[min]]) {
            index[min] = i;
        }
        i += 1;
    }

    return index;
}

function parse_recipes(pantry){
    matches = search_matches(pantry);
    top = top_five(matches);
    var i = 0;
    final = []
    while(i != top.length){
        final.push(recipes[top[i]]);
        i += 1;
    }
    return final;
}

/*
const pantry = ["egg", "vanilla", "pumpkin"]

final = parse_recipes(pantry);


var i = 0;
while(i != final.length){
    console.log(final[i].url);
    console.log(final[i].name);
    var j = 0;
    while(j != final[i].ingredients.length){
        console.log(final[i].ingredients[j]);
        j += 1;
    }
    console.log(final[i].preparation);
    i += 1;
}
*/